[tools]
node = "25.2.1"
pnpm = "10.25.0"

[env]
VITE_CLERK_PUBLISHABLE_KEY = "pk_test_Z3JlYXQtc3BhbmllbC03OC5jbGVyay5hY2NvdW50cy5kZXYk"
CLOUDFLARE_ACCOUNT_ID = "5796b41bb99c92705af706d23abb0989"
VITE_CONVEX_URL = "https://dependable-wolverine-235.convex.cloud"
