[tools]
node = "25.2.1"
pnpm = "10.25.0"

[env]
_.path = ["{{config_root}}/node_modules/.bin"]
VITE_CLERK_PUBLISHABLE_KEY = "pk_test_Z3JlYXQtc3BhbmllbC03OC5jbGVyay5hY2NvdW50cy5kZXYk"

[settings]
experimental = true
